[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[context.production.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[context.deploy-preview.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
